kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: netdata
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: netdata
subjects:
- kind: ServiceAccount
  name: default
  namespace: netdata
roleRef:
  kind: ClusterRole
  name: netdata
  apiGroup: rbac.authorization.k8s.io
