apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-daemonset-proxy
  namespace: kube-daemonset-proxy
  labels:
    app: kube-daemonset-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-daemonset-proxy
  template:
    metadata:
      labels:
        app: kube-daemonset-proxy
    spec:
      serviceAccountName: kube-daemonset-proxy
      containers:
      - name: proxy
        image: kube-daemonset-proxy
        imagePullPolicy: Never
        env:
        - name: KUBE_DS_PROXY_NAMESPACE
          value: netdata
        - name: KUBE_DS_PROXY_POD_PORT_NAME
          value: http
        - name: KUBE_DS_PROXY_LABEL_SELECTOR
          value: app=netdata
        - name: KUBE_DS_PROXY_TITLE
          value: Netdata
        - name: KUBE_DS_PROXY_LISTEN_ADDR
          value: ':8080'
        ports:
        - containerPort: 8080
