kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: netdata
  name: kube-daemonset-proxy
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: netdata
  name: kube-daemonset-proxy
subjects:
- kind: ServiceAccount
  name: kube-daemonset-proxy
  namespace: kube-daemonset-proxy
roleRef:
  kind: Role
  name: kube-daemonset-proxy
  apiGroup: rbac.authorization.k8s.io
