kind: Service
apiVersion: v1
metadata:
  name: kube-daemonset-proxy
  namespace: kube-daemonset-proxy
  labels:
    app: kube-daemonset-proxy
spec:
  type: NodePort
  selector:
    app: kube-daemonset-proxy
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
